apiVersion: v1
kind: Service
metadata:
  name: ujumbe
spec:
  selector:
    app: ujumbe
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110
  