name: Node.js CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: $HOME/.kube/config
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA2U6SKQKMMCCAHDWF # ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: JBA6YCFGsVW3zBo4buUCRlg8W8vb2tT7cJxmbMYH # ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Change to your desired AWS region

      - name: Authenticate with AWS ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j9c2n9s8
        env:
          your-region: us-east-2 # Change to your AWS region
          your-account-id: 732196143768 # Change to your AWS account ID

      - name: Build and push Docker image
        run: |
          # Replace these with your Docker image details
          
          docker build -t ujumbe:latest .
          docker tag ujumbe:latest public.ecr.aws/j9c2n9s8/ujumbe:latest
          docker push public.ecr.aws/j9c2n9s8/ujumbe:latest
        env:
          DOCKER_CLI_AK: AKIA2U6SKQKMMCCAHDWF # ${{ secrets.AWS_ACCESS_KEY_ID }}
          DOCKER_CLI_SK: JBA6YCFGsVW3zBo4buUCRlg8W8vb2tT7cJxmbMYH # ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2 # Change to your desired AWS region

      - name: Generate ConfigMap
        run: |
          echo "apiVersion: v1" > configmap.yaml
          echo "kind: ConfigMap" >> configmap.yaml
          echo "metadata:" >> configmap.yaml
          echo "  name: ujumbe-config" >> configmap.yaml
          echo "data:" >> configmap.yaml
          echo "  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}" >> configmap.yaml
          echo "  MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}" >> configmap.yaml
           echo "  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}" >> configmap.yaml
          echo "  TEST_BUSINESS_NAME: ${{ secrets.TEST_BUSINESS_NAME }}" >> configmap.yaml
          echo "  TEST_FROM_EMAIL: ${{ secrets.TEST_FROM_EMAIL }}" >> configmap.yaml
          echo "  TEST_TO_EMAIL: ${{ secrets.TEST_TO_EMAIL }}" >> configmap.yaml
         
          # Add more environment variables as needed
     

      - name: Deploy to EKS
        run: |
          
          # Install and configure kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          # Authenticate with EKS cluster
          aws eks --region us-east-2 update-kubeconfig --name ujumbe-app
          kubectl rollout restart deployment/ujumbe  
          # Apply Kubernetes manifests
          
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f configmap.yaml
          # printenv | sort

        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Display Pod Logs
        run: |
          
          # show the logs
          # printenv | sort
           
          kubectl wait --for=condition=available deployment/ujumbe --timeout=360s
          POD_NAME=$(kubectl get pods -l app=ujumbe -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD_NAME

