name: Node.js CI

env:
  SLACK_WEBHOOK: ${{secrets.API_KEY}}

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci


      - name: Build
        run: npm run build --if-present


      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA2U6SKQKMMCCAHDWF # ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: JBA6YCFGsVW3zBo4buUCRlg8W8vb2tT7cJxmbMYH # ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Change to your desired AWS region

      - name: Build and push Docker image
        run: |
          # Replace these with your Docker image details
          docker build -t your-docker-image:latest .
          docker tag your-docker-image:latest your-repo/your-docker-image:latest
          docker push your-repo/your-docker-image:latest
        env:
          DOCKER_CLI_AK: AKIA2U6SKQKMMCCAHDWF # ${{ secrets.AWS_ACCESS_KEY_ID }}
          DOCKER_CLI_SK: JBA6YCFGsVW3zBo4buUCRlg8W8vb2tT7cJxmbMYH # ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2 # Change to your desired AWS region

      - name: Deploy to EKS
        run: |
          # Install and configure kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
          # Authenticate with EKS cluster
          aws eks --region us-east-2 update-kubeconfig --name your-eks-cluster-name
          
          # Apply Kubernetes manifests
          kubectl apply -f your-kubernetes-manifests.yaml
        env:
          KUBECONFIG: $HOME/.kube/config
